"""add whatsapp gateway tables

Revision ID: 1cecbd439794
Revises: 24bcfbcc1ee9
Create Date: 2026-07-31 16:15:37.339160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1cecbd439794'
down_revision: Union[str, None] = '24bcfbcc1ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_gateway_status',
    sa.Column('connection_state', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whatsapp_groups',
    sa.Column('whatsapp_group_external_id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_monitored', sa.Boolean(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=True),
    sa.Column('supervisor_id', sa.String(), nullable=True),
    sa.Column('zone_label', sa.String(length=150), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whatsapp_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_groups_whatsapp_group_external_id'), ['whatsapp_group_external_id'], unique=True)

    op.create_table('whatsapp_messages',
    sa.Column('whatsapp_message_id', sa.String(length=200), nullable=False),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('group_external_id', sa.String(length=150), nullable=False),
    sa.Column('sender_external_id', sa.String(length=150), nullable=True),
    sa.Column('sender_name', sa.String(length=150), nullable=True),
    sa.Column('sender_phone', sa.String(length=30), nullable=True),
    sa.Column('message_date', sa.DateTime(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('caption_text', sa.String(length=2000), nullable=True),
    sa.Column('media_external_id', sa.String(length=200), nullable=True),
    sa.Column('media_filename', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('download_status', sa.String(length=30), nullable=False),
    sa.Column('evidence_id', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('duplicate_of_message_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_message_id'], ['whatsapp_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['whatsapp_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whatsapp_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_messages_group_external_id'), ['group_external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_messages_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_messages_whatsapp_message_id'), ['whatsapp_message_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_messages_whatsapp_message_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_messages_sha256'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_messages_group_external_id'))

    op.drop_table('whatsapp_messages')
    with op.batch_alter_table('whatsapp_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_groups_whatsapp_group_external_id'))

    op.drop_table('whatsapp_groups')
    op.drop_table('whatsapp_gateway_status')
    # ### end Alembic commands ###
