"""add user security fields (must_change_password, lockout)

Revision ID: 24bcfbcc1ee9
Revises: 433dbdef25a3
Create Date: 2026-07-30 16:04:33.397645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '24bcfbcc1ee9'
down_revision: Union[str, None] = '433dbdef25a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default requis : ajout de colonnes NOT NULL sur une table qui
    # peut deja contenir des lignes (ex: l'administrateur initial existant).
    # Les comptes deja crees sont ainsi forces a changer leur mot de passe
    # au prochain login (comportement voulu, pas un accident).
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.true())
        )
        batch_op.add_column(
            sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(sa.Column('locked_until', sa.String(length=50), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
